name: Docker CD

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  # Build the image
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4

      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          
      - name: build and tag
        run: |
          docker build -t fasilcv/myapp:"${VERSION}" .
          docker tag fasilcv/myapp:"${VERSION}" fasilcv/myapp:latest

      - name: save image
        run: docker save -o myapp.tar fasilcv/myapp:"${VERSION}"
      
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: myapp.tar
  
  # Test the image
  test-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load docker image
        run: docker load -i myapp.tar

      - name: Run docker image
        run: |
          docker run -d --name=myapp -p 8080:80 fasilcv/myapp:"${VERSION}"
          sleep 3
      
      - name: Helath check
        run: |
          curl -f http://localhost:8080/healthz
  # Push image
  push:
    needs: [ test-image ]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Image push 
        run: echo "Push image to docker registry"
